apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: targeting-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpZS21zaW9sTW5OU0d5MXZNdk5WeUB0Yy1wcm9kLXJkcy10YXJnZXRpbmcuY2tqY2s0NG8yY3hnLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3RhcmdldGluZ19kYg==