apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-configmap
  namespace: targeting
data:
  PORT: "8003"
  AUTH_SERVICE_URL: "http://auth-service.auth.svc.cluster.local:8001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-deployment
  namespace: targeting
  labels:
    app: targeting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: targeting
  template:
    metadata:
      labels:
        app: targeting
    spec:
      containers:
      - name: targeting-container
        image: 047719652987.dkr.ecr.us-east-1.amazonaws.com/tc-prod-ecr-targeting:c82675ff
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "40m"
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: targeting-configmap
        - secretRef:
            name: targeting-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: targeting-ingress
  namespace: targeting
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /targeting(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: targeting-service
            port:
              number: 8003
---
apiVersion: v1
kind: Namespace
metadata:
  name: targeting
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: targeting-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpZS21zaW9sTW5OU0d5MXZNdk5WeUB0Yy1wcm9kLXJkcy10YXJnZXRpbmcuY2tqY2s0NG8yY3hnLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3RhcmdldGluZ19kYg==
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting
spec:
  selector:
    app: targeting
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP