apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: auth-secret
  namespace: toggle
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpPeGROWDNrVE82UkUwQUlmb0daMEB0Yy1wcm9kLXJkcy1hdXRoLmNramNrNDRvMmN4Zy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9hdXRoX2Ri
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=