apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: flag-secret
  namespace: flag
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpLY1k4TkpRQUQxTWFLTkNUQUJ0a0B0Yy1wcm9kLXJkcy1mbGFnLmNramNrNDRvMmN4Zy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9mbGFnc19kYg==