apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: flag-secret
  namespace: toggle
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpLY1k4TkpRQUQxTWFLTkNUQUJ0a0B0Yy1wcm9kLXJkcy1mbGFncy5ja2pjazQ0bzJjeGcudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ3NfZGI=