# ============================================
# WORKFLOW: Deploy da imagem para ECR
# Automatiza build e deploy da aplicação
# ============================================
name: CI - auth

on:
#  push:
#    branches: [main]
  workflow_dispatch:  # Permite execução manual

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: tc-prod-ecr-auth

permissions:
  id-token: write   # Permissão para autenticar em prod
  contents: read

jobs:
  # ============================================
  # JOB: Build do código
  # ============================================
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./auth-service-main

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
  # ============================================
  # JOB: Build da imagem e Deploy
  # ============================================
  deploy:
    name: Build da imagem e Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup
        id: build-setup
        run: echo "short-sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT


      # Step 1: Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_GITHUB_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Login no ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

#      # Step 4: Build e Push da imagem
#      - name: Build and push Docker image
#        id: build-image
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build --platform linux/amd64 \
#            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
#            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
#          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Step 4: Build e Push da imagem
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHORT_SHA: ${{ steps.build-setup.outputs.short-sha }}
        with:
          context: ./auth-service-main
          file: ./auth-service-main/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
        