# ============================================
# WORKFLOW: Deploy da imagem para ECR
# Automatiza build e deploy da aplicação
# ============================================
name: CI - flag

on:
#  push:
#    branches: [main]
  workflow_dispatch:  # Permite execução manual

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: tc-prod-ecr-flag
  WORK_DIR: flag-service-main
  ARGO_DIR: .kubernetes/overlays/production
  ARGO_APP: flag-service

permissions:
  id-token: write   # Permissão para autenticar em prod
  contents: read

jobs:
  # ============================================
  # JOB: Lint (Verificação de erros no código)
  # ============================================
  lint:
    name: Lint com Pylint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ env.WORK_DIR }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pylint
      run: |
        pylint --errors-only $(git ls-files '*.py')


  # ============================================
  # JOB: SCA (vulnerabilidades de dependencias)
  # ============================================
  sca:
    name: SCA com Trivy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ env.WORK_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './${{ env.WORK_DIR }}'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'


  # ============================================
  # JOB: SAST (vulnerabilidades no código)
  # ============================================
  sast:
    name: SAST com bandit
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ env.WORK_DIR }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit SAST scan
      run: |
        bandit -r . -lll -iii


  # ============================================
  # JOB: Build da imagem e Scan
  # ============================================
  image-scan:
    name: Build da imagem e Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.WORK_DIR }}
          file: ./${{ env.WORK_DIR }}/Dockerfile
          load: true
          tags: my-app:latest

      - name: Run Trivy container image scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:latest'
          scan-type: 'image'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'


  # ============================================
  # JOB: Build da imagem e Scan
  # ============================================
  deploy:
    name: Build da imagem e Deploy
    runs-on: ubuntu-latest
    needs: [lint, sca, sast, image-scan]

    steps:
      - name: Setup
        id: build-setup
        run: echo "short-sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_GITHUB_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHORT_SHA: ${{ steps.build-setup.outputs.short-sha }}
        with:
          context: ./${{ env.WORK_DIR }}
          file: ./${{ env.WORK_DIR }}/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}


  # ============================================
  # JOB: Atualizando git com nova imagem
  # ============================================
  update-manifest:
    name: Atualizando git com nova imagem
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup
        id: update-setup
        run: echo "short-sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Update Kubernetes Manifest
        env:
          NEW_IMAGE: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ steps.update-setup.outputs.short-sha }}"
        run: |
          yq e -i '.spec.template.spec.containers[0].image = env(NEW_IMAGE)' ${{ env.WORK_DIR }}/k8s/deployment.yaml

      - name: Concat k8s files
        run: |
          yq eval-all '.' ${{ env.WORK_DIR }}/k8s/*.yaml > ${{ env.ARGO_DIR }}/${{ env.ARGO_APP }}.yml
  
      - name: Commit and Push Changes
        working-directory: ${{ env.ARGO_DIR }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add ${{ env.ARGO_APP }}.yaml
          
          # Only commit if changes were detected
          if git diff --staged --quiet; then
            echo "No manifest changes to commit."
          else
            git commit -m "ci: update container image to ${{ steps.update-setup.outputs.short-sha }} [skip ci]"
            git push
          fi