apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evaluation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-app-repo.git'
    targetRevision: main
    path: 'evaluation-service-main/k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: evaluation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true